# Generated by Django 3.1.7 on 2021-04-10 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_option', models.IntegerField(choices=[(1, 'Push'), (2, 'Email'), (3, 'Both')], default=1)),
                ('home_view', models.IntegerField(choices=[(1, 'List')], default=1)),
                ('theme', models.IntegerField(choices=[(1, 'Light'), (2, 'Dark')], default=1)),
                ('date_view', models.IntegerField(choices=[(1, 'dd-mm-yyyy'), (2, 'yyyy-mm-dd'), (3, 'yyyy-dd-mm')], default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
