# Generated by Django 3.1.7 on 2021-04-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='home_view',
            field=models.IntegerField(choices=[(1, 'List'), (2, 'Daily'), (3, 'Weekly'), (4, 'Monthly')], default=1),
        ),
    ]
