# Generated by Django 3.1.7 on 2021-04-24 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210424_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='code',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_active',
        ),
    ]
