# Generated by Django 3.1.7 on 2021-02-28 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Task name')),
                ('description', models.CharField(max_length=2000, verbose_name='Description')),
                ('type', models.CharField(choices=[(0, 'Event'), (1, 'Task')], max_length=10, verbose_name='Event or Task')),
                ('deadline', models.DateTimeField(blank=True, verbose_name='Task deadline')),
            ],
        ),
    ]
