# Generated by Django 3.1.7 on 2021-04-04 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Task name')),
                ('description', models.CharField(max_length=2000, verbose_name='Description')),
                ('type', models.IntegerField(choices=[(0, 'Event'), (1, 'Task')], verbose_name='Event or Task')),
                ('deadline', models.DateTimeField(blank=True, verbose_name='Task deadline')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
