# Generated by Django 3.2 on 2021-05-11 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20210510_2122'),
        ('tasks', '0007_remove_task_type'),
    ]

    operations = [
    ]
